const mongoose = require('mongoose');
const Course = require('../models/Course');
require('dotenv').config();

const courses = [
  // JavaScript & Frontend (10 courses)
  {
    title: 'The Complete JavaScript Course 2024',
    platform: 'Udemy',
    instructor: 'Jonas Schmedtmann',
    url: 'https://www.udemy.com/course/the-complete-javascript-course/',
    description: 'Master JavaScript with modern ES6+, async/await, promises, and more',
    relatedSkills: ['JavaScript', 'ES6', 'Async/Await', 'DOM Manipulation'],
    duration: '69 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 145000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'React - The Complete Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/react-the-complete-guide/',
    description: 'Learn React hooks, Redux, routing, animations, Next.js',
    relatedSkills: ['React', 'Redux', 'React Hooks', 'Next.js', 'JavaScript'],
    duration: '49 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 180000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Modern JavaScript From The Beginning',
    platform: 'Udemy',
    instructor: 'Brad Traversy',
    url: 'https://www.udemy.com/course/modern-javascript-from-the-beginning/',
    description: 'Learn modern JavaScript from scratch',
    relatedSkills: ['JavaScript', 'DOM', 'Fetch API', 'ES6'],
    duration: '21 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 45000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Angular - The Complete Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/the-complete-guide-to-angular-2/',
    description: 'Master Angular and build awesome reactive apps',
    relatedSkills: ['Angular', 'TypeScript', 'RxJS', 'NgRx'],
    duration: '34 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 98000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Vue - The Complete Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/vuejs-2-the-complete-guide/',
    description: 'Vue.js is an awesome JavaScript framework',
    relatedSkills: ['Vue.js', 'Vuex', 'Vue Router', 'JavaScript'],
    duration: '31 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 75000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'TypeScript Course for Beginners',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=gp5H0Vw39yw',
    description: 'Learn TypeScript fundamentals',
    relatedSkills: ['TypeScript', 'JavaScript'],
    duration: '3 hours',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 15000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Advanced CSS and Sass',
    platform: 'Udemy',
    instructor: 'Jonas Schmedtmann',
    url: 'https://www.udemy.com/course/advanced-css-and-sass/',
    description: 'Master flexbox, CSS Grid, responsive design',
    relatedSkills: ['CSS', 'Sass', 'Flexbox', 'CSS Grid', 'Responsive Design'],
    duration: '28 hours',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 92000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'HTML and CSS for Beginners',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=mU6anWqZJcc',
    description: 'Complete HTML and CSS tutorial',
    relatedSkills: ['HTML', 'CSS'],
    duration: '11 hours',
    difficulty: 'Beginner',
    rating: 4.9,
    reviewCount: 25000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Tailwind CSS From Scratch',
    platform: 'Udemy',
    instructor: 'Brad Traversy',
    url: 'https://www.udemy.com/course/tailwind-from-scratch/',
    description: 'Learn utility-first CSS framework',
    relatedSkills: ['Tailwind CSS', 'CSS', 'Responsive Design'],
    duration: '12 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 12000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Bootstrap 5 Tutorial',
    platform: 'YouTube',
    instructor: 'Net Ninja',
    url: 'https://www.youtube.com/playlist?list=PL4cUxeGkcC9joIM91nLzd_qaH_AimmdAR',
    description: 'Learn Bootstrap 5 from scratch',
    relatedSkills: ['Bootstrap', 'CSS', 'Responsive Design'],
    duration: '3 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },

  // Backend & Databases (15 courses)
  {
    title: 'Node.js, Express, MongoDB & More',
    platform: 'Udemy',
    instructor: 'Jonas Schmedtmann',
    url: 'https://www.udemy.com/course/nodejs-express-mongodb-bootcamp/',
    description: 'Master Node by building a real RESTful API',
    relatedSkills: ['Node.js', 'Express', 'MongoDB', 'REST API'],
    duration: '42 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 85000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Complete Python Bootcamp',
    platform: 'Udemy',
    instructor: 'Jose Portilla',
    url: 'https://www.udemy.com/course/complete-python-bootcamp/',
    description: 'Learn Python from basics to advanced',
    relatedSkills: ['Python', 'Programming', 'OOP'],
    duration: '22 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 475000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Python for Everybody',
    platform: 'Coursera',
    instructor: 'University of Michigan',
    url: 'https://www.coursera.org/specializations/python',
    description: 'Learn to Program and Analyze Data with Python',
    relatedSkills: ['Python', 'Data Analysis', 'SQL'],
    duration: '8 months',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 320000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Django for Beginners',
    platform: 'Udemy',
    instructor: 'Nick Walter',
    url: 'https://www.udemy.com/course/django-for-beginners/',
    description: 'Build websites with Python and Django',
    relatedSkills: ['Django', 'Python', 'Web Development'],
    duration: '8 hours',
    difficulty: 'Beginner',
    rating: 4.5,
    reviewCount: 12000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Flask Web Development',
    platform: 'YouTube',
    instructor: 'Corey Schafer',
    url: 'https://www.youtube.com/playlist?list=PL-osiE80TeTs4UjLw5MM6OjgkjFeUxCYH',
    description: 'Build web applications with Flask',
    relatedSkills: ['Flask', 'Python', 'REST API'],
    duration: '10 hours',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 15000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'FastAPI - The Complete Course',
    platform: 'Udemy',
    instructor: 'Sanjeev Thiyagarajan',
    url: 'https://www.udemy.com/course/fastapi-the-complete-course/',
    description: 'Build fast APIs with Python',
    relatedSkills: ['FastAPI', 'Python', 'REST API'],
    duration: '19 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 8500,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Java Programming Masterclass',
    platform: 'Udemy',
    instructor: 'Tim Buchalka',
    url: 'https://www.udemy.com/course/java-the-complete-java-developer-course/',
    description: 'Learn Java from zero to expert',
    relatedSkills: ['Java', 'Programming', 'OOP'],
    duration: '80 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 180000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Spring Boot Microservices',
    platform: 'Udemy',
    instructor: 'in28Minutes',
    url: 'https://www.udemy.com/course/microservices-with-spring-boot-and-spring-cloud/',
    description: 'Master Microservices with Spring Boot',
    relatedSkills: ['Spring Boot', 'Java', 'Microservices'],
    duration: '21 hours',
    difficulty: 'Advanced',
    rating: 4.5,
    reviewCount: 45000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'The Complete SQL Bootcamp',
    platform: 'Udemy',
    instructor: 'Jose Portilla',
    url: 'https://www.udemy.com/course/the-complete-sql-bootcamp/',
    description: 'Master SQL and PostgreSQL',
    relatedSkills: ['SQL', 'PostgreSQL', 'Database'],
    duration: '9 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 140000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'MongoDB - The Complete Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/mongodb-the-complete-developers-guide/',
    description: 'Master MongoDB for web & mobile apps',
    relatedSkills: ['MongoDB', 'NoSQL', 'Database'],
    duration: '17 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 45000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Redis Crash Course',
    platform: 'YouTube',
    instructor: 'Brad Traversy',
    url: 'https://www.youtube.com/watch?v=jgpVdJB2sKQ',
    description: 'Learn Redis in one video',
    relatedSkills: ['Redis', 'Caching', 'Database'],
    duration: '1 hour',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 12000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'GraphQL with Node.js',
    platform: 'Udemy',
    instructor: 'Stephen Grider',
    url: 'https://www.udemy.com/course/graphql-with-react-course/',
    description: 'Build APIs with GraphQL and Apollo',
    relatedSkills: ['GraphQL', 'Node.js', 'Apollo'],
    duration: '13 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 25000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'REST API Design Best Practices',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=-MTSQjw5DrM',
    description: 'Learn REST API design principles',
    relatedSkills: ['REST API', 'API Design', 'Backend'],
    duration: '2 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Ruby on Rails Tutorial',
    platform: 'Udemy',
    instructor: 'Rob Percival',
    url: 'https://www.udemy.com/course/the-complete-ruby-on-rails-developer-course/',
    description: 'Learn to build web apps with Rails',
    relatedSkills: ['Ruby', 'Ruby on Rails', 'Web Development'],
    duration: '45 hours',
    difficulty: 'Beginner',
    rating: 4.5,
    reviewCount: 35000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'PHP for Beginners',
    platform: 'YouTube',
    instructor: 'Traversy Media',
    url: 'https://www.youtube.com/watch?v=OK_JCtrrv-c',
    description: 'Learn PHP from scratch',
    relatedSkills: ['PHP', 'Web Development', 'MySQL'],
    duration: '4 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 18000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
    // DevOps & Cloud (10 courses)
  {
    title: 'Docker and Kubernetes: The Complete Guide',
    platform: 'Udemy',
    instructor: 'Stephen Grider',
    url: 'https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/',
    description: 'Build, test, and deploy Docker applications with Kubernetes',
    relatedSkills: ['Docker', 'Kubernetes', 'DevOps', 'CI/CD'],
    duration: '22 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 98000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'AWS Certified Solutions Architect',
    platform: 'Udemy',
    instructor: 'Stephane Maarek',
    url: 'https://www.udemy.com/course/aws-certified-solutions-architect-associate/',
    description: 'Pass the AWS Solutions Architect Associate Exam',
    relatedSkills: ['AWS', 'Cloud Computing', 'Cloud Architecture'],
    duration: '27 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 125000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Azure Fundamentals',
    platform: 'Microsoft Learn',
    instructor: 'Microsoft',
    url: 'https://learn.microsoft.com/en-us/training/paths/azure-fundamentals/',
    description: 'Learn Azure cloud fundamentals',
    relatedSkills: ['Azure', 'Cloud Computing', 'Microsoft Cloud'],
    duration: '10 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 45000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Google Cloud Platform Fundamentals',
    platform: 'Coursera',
    instructor: 'Google Cloud',
    url: 'https://www.coursera.org/learn/gcp-fundamentals',
    description: 'Introduction to Google Cloud Platform',
    relatedSkills: ['GCP', 'Google Cloud', 'Cloud Computing'],
    duration: '15 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 28000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Jenkins Tutorial for Beginners',
    platform: 'YouTube',
    instructor: 'Simplilearn',
    url: 'https://www.youtube.com/watch?v=FX322RVNGj4',
    description: 'Learn Jenkins CI/CD pipeline',
    relatedSkills: ['Jenkins', 'CI/CD', 'DevOps'],
    duration: '8 hours',
    difficulty: 'Beginner',
    rating: 4.5,
    reviewCount: 12000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Terraform for Beginners',
    platform: 'Udemy',
    instructor: 'Zeal Vora',
    url: 'https://www.udemy.com/course/terraform-for-the-absolute-beginners/',
    description: 'Learn Infrastructure as Code with Terraform',
    relatedSkills: ['Terraform', 'Infrastructure as Code', 'DevOps'],
    duration: '4 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 18000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Ansible for Beginners',
    platform: 'YouTube',
    instructor: 'TechWorld with Nana',
    url: 'https://www.youtube.com/watch?v=1id6ERvfozo',
    description: 'Configuration management with Ansible',
    relatedSkills: ['Ansible', 'Configuration Management', 'DevOps'],
    duration: '2 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 15000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'GitHub Actions Tutorial',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=R8_veQiYBjI',
    description: 'Automate your workflow with GitHub Actions',
    relatedSkills: ['GitHub Actions', 'CI/CD', 'DevOps'],
    duration: '2 hours',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 10000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Linux Administration Bootcamp',
    platform: 'Udemy',
    instructor: 'Jason Cannon',
    url: 'https://www.udemy.com/course/linux-administration-bootcamp/',
    description: 'Master Linux system administration',
    relatedSkills: ['Linux', 'System Administration', 'DevOps'],
    duration: '8 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 35000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Nginx Fundamentals',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=7VAI73roXaY',
    description: 'High Performance Load Balancer with Nginx',
    relatedSkills: ['Nginx', 'Web Server', 'Load Balancing'],
    duration: '3 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },

  // Machine Learning & AI (8 courses)
  {
    title: 'Machine Learning A-Z',
    platform: 'Udemy',
    instructor: 'Kirill Eremenko',
    url: 'https://www.udemy.com/course/machinelearning/',
    description: 'Learn Machine Learning in Python and R',
    relatedSkills: ['Machine Learning', 'Python', 'Data Science', 'TensorFlow'],
    duration: '44 hours',
    difficulty: 'Intermediate',
    rating: 4.5,
    reviewCount: 175000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Deep Learning Specialization',
    platform: 'Coursera',
    instructor: 'Andrew Ng',
    url: 'https://www.coursera.org/specializations/deep-learning',
    description: 'Master Deep Learning fundamentals',
    relatedSkills: ['Deep Learning', 'Neural Networks', 'TensorFlow', 'PyTorch'],
    duration: '3 months',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviewCount: 120000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'TensorFlow Developer Certificate',
    platform: 'Coursera',
    instructor: 'deeplearning.ai',
    url: 'https://www.coursera.org/professional-certificates/tensorflow-in-practice',
    description: 'Build and train neural networks with TensorFlow',
    relatedSkills: ['TensorFlow', 'Deep Learning', 'Python'],
    duration: '4 months',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 45000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'PyTorch for Deep Learning',
    platform: 'Udemy',
    instructor: 'Jose Portilla',
    url: 'https://www.udemy.com/course/pytorch-for-deep-learning-with-python-bootcamp/',
    description: 'Learn PyTorch for building neural networks',
    relatedSkills: ['PyTorch', 'Deep Learning', 'Python'],
    duration: '16 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 28000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Natural Language Processing',
    platform: 'Coursera',
    instructor: 'deeplearning.ai',
    url: 'https://www.coursera.org/specializations/natural-language-processing',
    description: 'Master NLP with sequence models',
    relatedSkills: ['NLP', 'Deep Learning', 'Python', 'TensorFlow'],
    duration: '4 months',
    difficulty: 'Advanced',
    rating: 4.7,
    reviewCount: 18000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Computer Vision Basics',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=01sAkU_NvOY',
    description: 'Learn computer vision with OpenCV',
    relatedSkills: ['Computer Vision', 'OpenCV', 'Python'],
    duration: '4 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 12000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Data Science and Machine Learning Bootcamp',
    platform: 'Udemy',
    instructor: 'Jose Portilla',
    url: 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
    description: 'Learn Data Science, ML, and Python',
    relatedSkills: ['Data Science', 'Machine Learning', 'Python', 'Pandas', 'NumPy'],
    duration: '25 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 125000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Scikit-Learn Tutorial',
    platform: 'YouTube',
    instructor: 'Keith Galli',
    url: 'https://www.youtube.com/watch?v=pqNCD_5r0IU',
    description: 'Machine Learning with Scikit-Learn',
    relatedSkills: ['Scikit-learn', 'Machine Learning', 'Python'],
    duration: '2 hours',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },

  // Mobile Development (6 courses)
  {
    title: 'React Native - The Practical Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/react-native-the-practical-guide/',
    description: 'Build iOS and Android apps with React Native',
    relatedSkills: ['React Native', 'Mobile Development', 'React', 'JavaScript'],
    duration: '33 hours',
    difficulty: 'Intermediate',
    rating: 4.6,
    reviewCount: 58000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Flutter & Dart - The Complete Guide',
    platform: 'Udemy',
    instructor: 'Maximilian Schwarzmüller',
    url: 'https://www.udemy.com/course/learn-flutter-dart-to-build-ios-android-apps/',
    description: 'Build iOS and Android apps with Flutter',
    relatedSkills: ['Flutter', 'Dart', 'Mobile Development'],
    duration: '43 hours',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 75000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'iOS Development with Swift',
    platform: 'Udemy',
    instructor: 'Angela Yu',
    url: 'https://www.udemy.com/course/ios-13-app-development-bootcamp/',
    description: 'Complete iOS app development course',
    relatedSkills: ['Swift', 'iOS Development', 'Xcode', 'SwiftUI'],
    duration: '62 hours',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 95000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Android Development with Kotlin',
    platform: 'Udemy',
    instructor: 'Denis Panjuta',
    url: 'https://www.udemy.com/course/android-kotlin-developer/',
    description: 'Build Android apps with Kotlin',
    relatedSkills: ['Kotlin', 'Android Development', 'Mobile Development'],
    duration: '41 hours',
    difficulty: 'Beginner',
    rating: 4.5,
    reviewCount: 42000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'SwiftUI Masterclass',
    platform: 'Udemy',
    instructor: 'Robert Petras',
    url: 'https://www.udemy.com/course/swiftui-masterclass-course-ios-development-with-swift/',
    description: 'Master SwiftUI for iOS development',
    relatedSkills: ['SwiftUI', 'Swift', 'iOS Development'],
    duration: '14 hours',
    difficulty: 'Intermediate',
    rating: 4.7,
    reviewCount: 12000,
    price: { amount: 84.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Jetpack Compose Tutorial',
    platform: 'YouTube',
    instructor: 'Philipp Lackner',
    url: 'https://www.youtube.com/playlist?list=PLQkwcJG4YTCSV7HdL-h3z3gSP47VvQ9Yn',
    description: 'Modern Android UI with Jetpack Compose',
    relatedSkills: ['Jetpack Compose', 'Kotlin', 'Android Development'],
    duration: '10 hours',
    difficulty: 'Intermediate',
    rating: 4.8,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },

  // Tools & Version Control (5 courses)
  {
    title: 'Git Complete: The Definitive Guide',
    platform: 'Udemy',
    instructor: 'Jason Taylor',
    url: 'https://www.udemy.com/course/git-complete/',
    description: 'Master Git and GitHub',
    relatedSkills: ['Git', 'GitHub', 'Version Control'],
    duration: '6 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 35000,
    price: { amount: 54.99, currency: 'USD', isFree: false },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Git and GitHub for Beginners',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=RGOj5yH7evk',
    description: 'Learn Git and GitHub from scratch',
    relatedSkills: ['Git', 'GitHub', 'Version Control'],
    duration: '1 hour',
    difficulty: 'Beginner',
    rating: 4.9,
    reviewCount: 25000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'VS Code Tutorial for Beginners',
    platform: 'YouTube',
    instructor: 'freeCodeCamp',
    url: 'https://www.youtube.com/watch?v=WPqXP_kLzpo',
    description: 'Master VS Code editor',
    relatedSkills: ['VS Code', 'IDE', 'Development Tools'],
    duration: '2 hours',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 15000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'Postman API Testing',
    platform: 'YouTube',
    instructor: 'Automation Step by Step',
    url: 'https://www.youtube.com/watch?v=VywxIQ2ZXw4',
    description: 'API testing with Postman',
    relatedSkills: ['Postman', 'API Testing', 'REST API'],
    duration: '2 hours',
    difficulty: 'Beginner',
    rating: 4.7,
    reviewCount: 12000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'JIRA Tutorial for Beginners',
    platform: 'YouTube',
    instructor: 'Simplilearn',
    url: 'https://www.youtube.com/watch?v=uM_m6EzMg3k',
    description: 'Project management with JIRA',
    relatedSkills: ['JIRA', 'Project Management', 'Agile'],
    duration: '1 hour',
    difficulty: 'Beginner',
    rating: 4.6,
    reviewCount: 8000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },

  // Free & Essential Courses (5 courses)
  {
    title: 'CS50: Introduction to Computer Science',
    platform: 'edX',
    instructor: 'David J. Malan',
    url: 'https://www.edx.org/course/cs50s-introduction-to-computer-science',
    description: 'Harvard\'s intro to computer science',
    relatedSkills: ['Programming Fundamentals', 'C', 'Python', 'SQL'],
    duration: '12 weeks',
    difficulty: 'Beginner',
    rating: 4.9,
    reviewCount: 50000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'Responsive Web Design',
    platform: 'Other',
    instructor: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    description: 'Learn HTML, CSS, and responsive design',
    relatedSkills: ['HTML', 'CSS', 'Responsive Design'],
    duration: '300 hours',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 120000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'JavaScript Algorithms and Data Structures',
    platform: 'Other',
    instructor: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    description: 'Master algorithms and data structures',
    relatedSkills: ['JavaScript', 'Algorithms', 'Data Structures'],
    duration: '300 hours',
    difficulty: 'Intermediate',
    rating: 4.9,
    reviewCount: 95000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: true,
    isActive: true
  },
  {
    title: 'The Odin Project - Full Stack JavaScript',
    platform: 'Other',
    instructor: 'The Odin Project',
    url: 'https://www.theodinproject.com/paths/full-stack-javascript',
    description: 'Free full-stack JavaScript curriculum',
    relatedSkills: ['JavaScript', 'Node.js', 'React', 'MongoDB', 'Full Stack'],
    duration: '6 months',
    difficulty: 'Beginner',
    rating: 4.8,
    reviewCount: 35000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  },
  {
    title: 'MIT OpenCourseWare - Introduction to Programming',
    platform: 'Other',
    instructor: 'MIT',
    url: 'https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/',
    description: 'MIT\'s intro to programming course',
    relatedSkills: ['Python', 'Programming Fundamentals', 'Computer Science'],
    duration: '9 weeks',
    difficulty: 'Beginner',
    rating: 4.9,
    reviewCount: 28000,
    price: { amount: 0, currency: 'USD', isFree: true },
    language: 'English',
    certificate: false,
    isActive: true
  }
];


// Seed function remains the same
const seedCourses = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await Course.deleteMany({});
    console.log('🗑️  Cleared existing courses');

    const inserted = await Course.insertMany(courses);
    console.log(`✅ Inserted ${inserted.length} courses`);

    console.log('\n📚 Courses Added:');
    inserted.forEach((course, index) => {
      console.log(`${index + 1}. ${course.title} (${course.platform}) - ${course.difficulty}`);
    });

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding courses:', error);
    process.exit(1);
  }
};

seedCourses();
